title:             SIGIR Beijing Chapter
description:       SIGIR Beijing Chapter
author:            SIGIR Beijing Chapter
baseurl:           ""
url:               "http://0.0.0.0:4000"

weibo_icon:        img/icon/weibo.png
email_icon:        img/icon/email.png

# Social Profiles
email:  your-email@example.com
weibo_username:   xinhuashidian

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
